### PR TITLE
Add jitsi-universe parent pom, cleanup pom

### PR DESCRIPTION
**Pull request by champtar**
Signed-off-by: Etienne CHAMPETIER champetier.etienne@gmail.com

### CODE REVIEW

**Comment by ibauersachs** [comment]
I'm not keen on merging this. Thr pom comes from the upstream project and I'd try to keep changes to it to a minimum.

**Comment by champtar** [comment]
This repo is a fork ... (for exemple jain-sdp doesn't exist in master)
I'm not changing any build dependency, just plugins and compiler source/target (1.5 -> 1.7)

Maybe I'm too new to Java but having 10 versions of the same lib/plugin in a project and targeting ancient version (1.5) disturbs me a bit.

**Comment by ibauersachs** [comment]
Maybe I'm too new to Maven, but jain-X being an external lib, this really doesn't matter. I agree on using the -universe and consistent versions for our own projects, but not on forks.

**Comment by champtar** [comment]
I agree it doesn't change anything.
I'm building everything from source (with gitsubmodules) and was just cleaning up has much as possible.

**Pull request closed without merging**
